[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Admin path protection
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Campaign page
[[redirects]]
  from = "/campaign"
  to = "/campaign.html"
  status = 301

# Staff page
[[redirects]]
  from = "/staff"
  to = "/staff.html"
  status = 301

# Services page
[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 301

# About page
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

# Company page
[[redirects]]
  from = "/company"
  to = "/company.html"
  status = 301

# Works page
[[redirects]]
  from = "/works"
  to = "/works.html"
  status = 301

[context.production.environment]
  FIREBASE_CONFIG = "production"

[context.deploy-preview.environment]
  FIREBASE_CONFIG = "staging"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.firebaseio.com https://*.googleapis.com"

# Cache static assets
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images_*/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"